(function(){define("offre/affiner",["jquery","t5/core/zone","underscore","bootstrap/collapse"],function($,zoneManager,_){var salaireMinimumSelectionne="";var dureeContratHebdoMinSelectionne="";var dureeContratHebdoMaxSelectionne="";var dureeContratMinimumSelectionne="";var dureeContratMaximumSelectionne="";var soumettreFormulaireAvecDelai;var delaySansRienSaisir=_.debounce(soumettreFormulaireDirect,3E3);function intPlierDeplierCollapseCritere(criteresObjects){if(criteresObjects.typeContrat){$("#collapseMore-1").toggleClass("in");
$("#ui-collapse-74").attr("aria-expanded",true).toggleClass("collapsed")}if(criteresObjects.contratSpecifique){$("#collapseMore-2").toggleClass("in");$("#ui-collapse-925").attr("aria-expanded",true).toggleClass("collapsed")}if(criteresObjects.dureeContrat)$("#duree_contrat").toggleClass("in");if(criteresObjects.tempsPartiel)$("#collapseLevel-dureehebdo").toggleClass("in")}function initSalaireMinimum(){salaireMinimumSelectionne=parseFloat(Math.round($("#idsalaireBrutMinimum").val()*100)/100).toFixed(2);
$("#idsalaireBrutMinimum").on("keyup",function(event){setTimeout(function(){if(!$("#typeSalaire").is(":visible")){var nouvelleValeurSalaire=parseFloat(Math.round($("#idsalaireBrutMinimum").val()*100)/100).toFixed(2);if(salaireMinimumSelectionne!==nouvelleValeurSalaire){tagDeClick({elem:this,chapter1:"Criteres",chapter2:"Activation",chapter3:"Salaire",name:nouvelleValeurSalaire+"_"+$("#boutonSalaire #salaireZone").text(),level2:91,type:"action"});delaySansRienSaisir();salaireMinimumSelectionne=nouvelleValeurSalaire}}},
1E3)})}function initTypeSalaire(){$("#typeSalaire a").on("click",function(event){var salaireMinimum=$('input[id*\x3d"idsalaireBrutMinimum"]').val();if(salaireMinimum){tagDeClick({elem:this,chapter1:"Criteres",chapter2:"Activation",chapter3:"Salaire",name:$('input[id*\x3d"idsalaireBrutMinimum"]').val()+"_"+$(event.target).text(),level2:91,type:"action"});mettreAJourTypeSalaire($(this).data("context"));if(!isCriteresInsuffisants())soumettreFormulaireAvecDelai();else soumettreFormulaireDirect()}})}function initInputTextPatternEtEmpecherCopierColler(){$("#filters input[type\x3dtext]").on("keypress",
function(event){var REG=/[0-9.,]/gi;var key=String.fromCharCode(event.which);return[8,9,37,39,46].indexOf(event.keyCode)!=-1||REG.test(key)});$("#filters input[type\x3dtext]").on("paste",function(e){e.preventDefault()})}function initAffichageDureeContrat(){$("#type_contrat input[type\x3dcheckbox]").on("change",function(event){var _dureeContratCollapse=$("#duree_contrat");var checkboxCollapse=$("#type_contrat input[type\x3dcheckbox]");var countMustCollapse=_.countBy(checkboxCollapse,function(contrat){return $(contrat).is(":checked")&&
($(contrat).attr("value")==="CDS"||($(contrat).attr("value")==="CDD"||($(contrat).attr("value")==="MIS"||$(contrat).attr("value")==="SAI")))}).true;if(countMustCollapse)_dureeContratCollapse.collapse("show");else{_dureeContratCollapse.collapse("hide");$("#idDureeContratMin").val("");$("#idDureeContratMax").val("")}})}function initDureeContrat(){dureeContratMinimumSelectionne=parseFloat(Math.round($("#idDureeContratMin").val()*100)/100).toFixed(2);dureeContratMaximumSelectionne=parseFloat(Math.round($("#idDureeContratMax").val()*
100)/100).toFixed(2);$(document).on("keyup",'#filters input[id*\x3d"idDureeContratMax"]',function(event){if(event.keyCode!==9)delaySansRienSaisir()});$("#idDureeContratMin").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeContratMax").is(":focus")){var nouvelleValeurDureeMin=parseFloat(Math.round($("#idDureeContratMin").val()*100)/100).toFixed(2);if(dureeContratMinimumSelectionne!==nouvelleValeurDureeMin){tagDeClick({elem:this,chapter1:"Criteres",chapter2:"Activation",chapter3:"Duree_contrat",
name:$("#idDureeContratMin").val()+"_a_"+$("#idDureeContratMax").val()+"_mois",level2:91,type:"action"});delaySansRienSaisir();dureeContratMinimumSelectionne=nouvelleValeurDureeMin}}},1E3)});$("#idDureeContratMax").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeContratMin").is(":focus")){var nouvelleValeurDureeMax=parseFloat(Math.round($("#idDureeContratMax").val()*100)/100).toFixed(2);if(dureeContratMaximumSelectionne!==nouvelleValeurDureeMax){tagDeClick({elem:this,chapter1:"Criteres",
chapter2:"Activation",chapter3:"Duree_contrat",name:$("#idDureeContratMin").val()+"_a_"+$("#idDureeContratMax").val()+"_mois",level2:91,type:"action"});delaySansRienSaisir();dureeContratMaximumSelectionne=nouvelleValeurDureeMax}}},1E3)})}function initAffichageDureeHebdo(){$("#duree_hebdomadaire input[type\x3dcheckbox]").on("change",function(){var _this=$(this);if(_this.attr("value")=="2")if(_this.is(":checked"))$("#collapseLevel-dureehebdo").collapse("show");else{$("#collapseLevel-dureehebdo").collapse("hide");
$("#idDureeHebdoMin").val("");$("#idDureeHebdoMax").val("")}})}function initDureeHebdo(){dureeContratHebdoMinSelectionne=parseFloat(Math.round($("#idDureeHebdoMin").val()*100)/100).toFixed(2);dureeContratHebdoMaxSelectionne=parseFloat(Math.round($("#idDureeHebdoMax").val()*100)/100).toFixed(2);$("#idDureeHebdoMax").on("keyup",function(event){if(event.keyCode!==9)delaySansRienSaisir()});$("#idDureeHebdoMin").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeHebdoMax").is(":focus")){var nouvelleValeurDureeHebdoMin=
parseFloat(Math.round($("#idDureeHebdoMin").val()*100)/100).toFixed(2);if(dureeContratHebdoMinSelectionne!==nouvelleValeurDureeHebdoMin){delaySansRienSaisir();dureeContratHebdoMinSelectionne=nouvelleValeurDureeHebdoMin}}},1E3)});$("#idDureeHebdoMax").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeHebdoMin").is(":focus")){var nouvelleValeurDureeHebdoMax=parseFloat(Math.round($("#idDureeHebdoMax").val()*100)/100).toFixed(2);if(dureeContratHebdoMaxSelectionne!==nouvelleValeurDureeHebdoMax){delaySansRienSaisir();
dureeContratHebdoMaxSelectionne=nouvelleValeurDureeHebdoMax}}},1E3)})}function initSubmitFilter(){initDebounce();$("#filters input[type\x3dcheckbox], #filters input[type\x3dradio], #filters select").on("change",function(event){var _this=$(this);var active="Activation";var elementDiv=$(_this.parents("div")[0]).attr("id").indexOf("Zone")>=0?$(_this.parents("div")[1]).attr("id"):$(_this.parents("div")[0]).attr("id");if($(_this.parents("div")[0]).attr("id").indexOf("collapse")>=0)elementDiv=$(_this.parents("div")[2]).attr("id");
if(elementDiv==="filters")elementDiv="contrat_specifique";var nameValue=_this.attr("value");if(_this.is("select"))nameValue=_this.val();if(elementDiv==="opportunites")nameValue=elementDiv;if(elementDiv==="niveau_formation"&&nameValue==="")nameValue="Tout_voir";if(_this.attr("id").indexOf("idDureeHebdoPartiel")>=0||_this.data("toggle")!=="collapse"){if(!_this.is(":checked")&&_this.attr("type")==="checkbox")active="Desactivation";if(elementDiv==="qualification")if(nameValue==="9")nameValue="Cadre";
else if(nameValue==="0")nameValue="Non_cadre";else if(nameValue==="X")nameValue="Non_precisee";if(!(_this.is("select")&&!_this.val())&&nameValue!=="null")tagDeClick({elem:this,chapter1:"Criteres",chapter2:active,chapter3:elementDiv,name:nameValue,level2:91,type:"action"});if(!isCriteresInsuffisants())soumettreFormulaireAvecDelai();else soumettreFormulaireDirect()}})}function isCriteresInsuffisants(){var motcles=$('select[id*\x3d"idmotsCles"]')[0];var lieux=$('select[id*\x3d"idlieux"]')[0];if($(motcles[0]).attr("value")||
($(lieux[0]).attr("value")||$(".filters-ext").is(":visible")))return false;return true}function soumettreFormulaireDirect(){$('form[id*\x3d"filtreForm"]').submit()}function initDebounce(){soumettreFormulaireAvecDelai=_.debounce(soumettreFormulaireDirect,1E3)}function initAffiner(data){initAffichageDureeContrat();initDureeContrat();initAffichageDureeHebdo();initDureeHebdo();initSubmitFilter();initInputTextPatternEtEmpecherCopierColler();intPlierDeplierCollapseCritere(data);initSalaireMinimum();initTypeSalaire()}
function mettreAJourTypeSalaire(typeSalaire){$("input[name\x3duniteSalaire]").val(typeSalaire)}return{init:initAffiner}})}).call(this);(function(){define("offre/contact",["jquery"],function($){function initSmartTagPartenaire(typeSalaire){$("a[id*\x3didLienPartenaire]").on("click",function(){var _this=$(this);tagDeClick({elem:this,chapter1:"Detail_offre",chapter2:"Candidature",chapter3:"Site_externe",name:"Postuler_"+_this.data("value"),level2:54,type:"exit"})})}return{init:initSmartTagPartenaire}})}).call(this);
(function(){define("offre/form-loading",["jquery","bootstrap/affix"],function($){return{init:init};function init(){$("#notifier").affix({offset:{top:180}})}})}).call(this);var LISTE_NOM_RECHERCHES_EXISTANTES;var URL_EVENT_ENREGISTRER;var URL_EVENT_REINIT;var ZONE_UPDATER;
(function(){define("offre/popinEnregistrerRecherche",["jquery","t5/core/zone","bootstrap/modal"],function($,zoneManager){ZONE_UPDATER=zoneManager;function initialiserLaPopin(params){URL_EVENT_ENREGISTRER=params.enregistrerRecherche;URL_EVENT_REINIT=params.reinitialisation;desactiverBoutonValider();jQuery("#PopinEnregistrer").unbind("show.bs.modal");jQuery("#PopinEnregistrer").on("show.bs.modal",function(e){$("[id^\x3dinfoNomRechercheExistant]").hide();$("[id^\x3derreur5RecherchesExistantes]").hide();
$("[id^\x3dzonePopinEnregistrerRecherche]").html("");ZONE_UPDATER.deferredZoneUpdate("zonePopinEnregistrerRecherche",URL_EVENT_REINIT)})}function callbackReinitialiserPopin(params){LISTE_NOM_RECHERCHES_EXISTANTES=params.nomsRechercheExistantes;reactiverBoutonValider()}function callbackEnregistrementRecherche(){reactiverBoutonValider()}function afficherLaPopin(){$("#PopinEnregistrer").modal("show");$("[id^\x3dnomRecherche]").focus()}return{initialiserLaPopin:initialiserLaPopin,afficherLaPopin:afficherLaPopin,
callbackReinitialiserPopin:callbackReinitialiserPopin,callbackEnregistrementRecherche:callbackEnregistrementRecherche}})}).call(this);function reactiverBoutonValider(){var boutonValider=$("#boutonValidePopinAbo");boutonValider.prop("disabled",false);boutonValider.removeClass("disabled")}function desactiverBoutonValider(){var boutonValider=$("#boutonValidePopinAbo");boutonValider.prop("disabled",true);boutonValider.addClass("disabled")}
function clicValiderEnregistrementAbo(){var nom=$("[id^\x3dnomRecherche]").val().trim();desactiverBoutonValider();if(nom==""){$("[id^\x3dinfoNomRechercheExistant]").hide();$("[id^\x3dnomRecherche]").parent().parent().addClass("has-error has-feedback");$("[id^\x3dnomRecherche]").parents().find(".help-block").show();reactiverBoutonValider();return false}else{$("[id^\x3dnomRecherche]").parent().parent().removeClass("has-error has-feedback");$("[id^\x3dnomRecherche]").parents().find(".help-block").hide();
if(LISTE_NOM_RECHERCHES_EXISTANTES)if($.inArray(nom.toLowerCase(),LISTE_NOM_RECHERCHES_EXISTANTES)>0&&$("[id^\x3dinfoNomRechercheExistant]").css("display")=="none"){$("[id^\x3derreur5RecherchesExistantes]").hide();$("[id^\x3dinfoNomRechercheExistant]").fadeIn();reactiverBoutonValider();return false}$("[id^\x3dnomRechercheExistant]").hide()}var param="";if(URL_EVENT_ENREGISTRER.indexOf("?")!=-1)param="\x26"+"nomRechercheOffre\x3d"+nom;else param="?"+"nomRechercheOffre\x3d"+nom;var mailActif=false;
if($("[id^\x3dmailOui]").is(":checked"))param=param+"\x26offresParMail\x3dtrue";param=param+"\x26offresParMail\x3d"+mailActif;ZONE_UPDATER.deferredZoneUpdate("zonePopinEnregistrerRecherche",URL_EVENT_ENREGISTRER+param)}
(function(){define("offre/popinErreurGenerique",["jquery","t5/core/ajax","bootstrap/modal"],function($,ajax){function initialisationPopinErreurGenerique(jsonPopin){if(jsonPopin!=null){if(jsonPopin.etat){$("#titrePopinErreurGenerique").text(jsonPopin.titrePopin);$("#texteContenuPopin1").text(jsonPopin.contenuPopin1);$("#texteContenuPopin2").text(jsonPopin.contenuPopin2);$("#PopinErreurGenerique").modal("show")}}else{$("#titrePopinErreurGenerique").text("titreDefault");$("#texteContenuPopin1").text("texte1Default");
$("#texteContenuPopin2").text("texte2Default");$("#PopinErreurGenerique").modal("show")}$(".modal-backdrop.fade.in").css("z-index",9998);$("#PopinDetails").css("z-index",1062)}return{initialisationPopinErreurGenerique:initialisationPopinErreurGenerique}})}).call(this);
(function(){define("offre/popinSignaler",["jquery","bootstrap/modal"],function($){function initialisationPopin(afficher){if(afficher===true)$("#PopinSignaler").modal("show")}function valueOrEmptyString(value){return value==undefined?"":value}function valueOrEmptyTab(tab){return tab==undefined?[]:tab}function initSmartTag(tagEtat){setTagDePage({chapter1:"Detail_offre",name:tagEtat,level2:91});setCustomVarsSite({technology:"Tapestry",category:"Candidat",authent:1,pn:"pn055"});dispatchSmartTagAvecVerification()}
return{initialisationPopin:initialisationPopin,initSmartTag:initSmartTag}})}).call(this);(function(){define("offre/popinEnvoiAmi",["bootstrap/modal"],function(){function initSmartTag(tagEtat,tagAuthent){setTagDePage({chapter1:"Detail_offre",name:tagEtat,level2:91});setCustomVarsSite({technology:"Tapestry",category:"Candidat",authent:tagAuthent,pn:"pn055"});dispatchSmartTagAvecVerification()}return{initSmartTag:initSmartTag}})}).call(this);
(function(){define("offre/recherches-enregistrees",["jquery","t5/core/ajax","isMobile"],function($,ajax,isMobile){return{init:init,afficherErreur:afficherErreur};function init(){$(document).on("click",'button[id*\x3d"confirmerProlongationAbonnements"]',function(event){ajax("/offres/mesrecherches:confirmerProlongationAbonnements",$.noop)});$(document).on("click",'button[id*\x3d"reactiverAbonnement"]',function(event){ajax("/offres/mesrecherches:activerAbonnement/"+event.currentTarget.dataset.idRecherche,
$.noop)});$(document).on("click",'button[id*\x3d"desactiverAbonnement"]',function(event){ajax("/offres/mesrecherches:desactiverAbonnement/"+event.currentTarget.dataset.idRecherche,$.noop)});$(document).on("click",'button[id*\x3d"preparerSuppressionRecherche"]',function(event){ajax("/offres/mesrecherches:preparerSuppressionRecherche/"+event.currentTarget.dataset.idRecherche,$.noop)});$(document).on("click",'button[id*\x3d"confirmerSuppressionRechercheEnregistree"]',function(event){ajax("/offres/mesrecherches:confirmerSuppressionRechercheEnregistree",
$.noop)})}function afficherErreur(){$("#ModalErreur").modal("show")}})}).call(this);
(function(){define("offre/selection",["jquery","t5/core/ajax","isMobile"],function($,ajax,isMobile){return{init:selection,ajoutOuSupprimerClassActiveDeLelement:ajoutOuSupprimerClassActiveDeLelement};function init(selection){selection.each(function(){var _this=$(this);var tooltip;if(_this.hasClass("active"))tooltip=_this.data("pressedTitle");else tooltip=_this.data("unpressedTitle");_this.attr("data-original-title",tooltip);if(!isMobile.any()){_this.tooltip&&_this.tooltip();_this.on("mouseleave",function(){_this.tooltip&&
_this.tooltip("hide")})}})}function selection(chapter1){var selection=$("*[data-selection]");init(selection);selection.off("click");selection.on("click",function(event){event.preventDefault();var _this=$(this);var idTarget=_this.data("target");var elementResultat=$(".result.active [data-selection]")||$(".result.seen.active [data-selection]");if(idTarget){$(idTarget).modal();$("#supprimerSelection").off("click");$("#supprimerSelection").on("click",function(){ajax(_this.attr("href"),{success:function(){$(idTarget).modal("hide");
$("#PopinDetails").modal("hide")}})})}else if(_this.hasClass("active")){var tooltip=_this.addClass("loading").data("unpressedTitle");$.ajax({url:_this.attr("href"),data:{ajout:false}}).done(function(){ajoutOuSupprimerClassActiveDeLelement(_this,false);ajoutOuSupprimerClassActiveDeLelement(elementResultat,false);$("#PopinIndisponibilite, #PopinErreurGenerique").off("show.bs.modal");$("#PopinIndisponibilite, #PopinErreurGenerique").on("show.bs.modal",function(event){ajoutOuSupprimerClassActiveDeLelement(_this,
true);ajoutOuSupprimerClassActiveDeLelement(elementResultat,true)});tagDeClick({elem:this,chapter1:chapter1,chapter2:"Ma_selection_offres",chapter3:"Desactivation",name:"Selectionner_une_offre",level2:91,type:"action"})}).fail(function(){_this.removeClass("loading")})}else{var tooltip=_this.addClass("loading").data("pressedTitle");var urlAjax=_this.attr("href");urlAjax+=urlAjax.indexOf("?")>0?"\x26":"?";urlAjax+="ajout\x3d"+true;var elementResultat=$(".result.active [data-selection]")||$(".result.seen.active [data-selection]");
ajax(urlAjax,{success:function(){ajoutOuSupprimerClassActiveDeLelement(_this,true);ajoutOuSupprimerClassActiveDeLelement(elementResultat,true);$("#PopinIndisponibilite, #PopinErreurGenerique").off("show.bs.modal");$("#PopinIndisponibilite, #PopinErreurGenerique").on("show.bs.modal",function(event){ajoutOuSupprimerClassActiveDeLelement(_this,false);ajoutOuSupprimerClassActiveDeLelement(elementResultat,false)});tagDeClick({elem:this,chapter1:chapter1,chapter2:"Ma_selection_offres",chapter3:"Activation",
name:"Selectionner_une_offre",level2:91,type:"action"})},failure:function(){_this.removeClass("loading")}})}})}function ajoutOuSupprimerClassActiveDeLelement(element,isAjout){var $element=$(element);if(isAjout)$element.addClass("active").attr("aria-pressed",true).attr("data-original-title",$element.data("pressedTitle"));else $element.removeClass("active").attr("aria-pressed",false).attr("data-original-title",$element.data("unpressedTitle"));if(!isMobile.any())$element.removeClass("loading").tooltip()}
})}).call(this);
(function(){define("offre/volet-detail",["jquery","offre/selection","t5/core/zone","t5/core/ajax","underscore"],function($,selection,zoneManager,ajax,_){return{init:activer,definirOffreCourante:definirOffreCourante,envoyerTags:envoyerTags,remiseEnPlaceFocus:remiseEnPlaceFocus,setFocusOnLinkSignaler:setFocusOnLinkSignaler};function setFocusOnLinkSignaler(){$("#PopinSignaler").one("hidden.bs.modal",function(){trapFocusVolet("#PopinDetails","add");$("#signalerOffreVolet").find(".text-link").focus()})}function setFocusOnOffresOnVoletHidden(){var popinDetails=
$("#PopinDetails");popinDetails.off("hidden.bs.modal");popinDetails.on("hidden.bs.modal",function(){var elementToFocus=$(".result[data-id-offre\x3d"+idOffreCourante+"] a");if(elementToFocus.length)elementToFocus[0].focus()})}var offres;var nbTotalOffres;var lienAfficherDetail;var boutonPrecedent;var boutonSuivant;var dataAttributeName;var indexOffreDemande;var idOffreCourante;var lire;function definirOffreCourante(idOffre){idOffreCourante=idOffre;setFocusOnOffresOnVoletHidden();$("#PopinDetails").on("hidden.bs.modal",
function(){history.back();setTimeout(function(){var url=window.location.href;url=removeURLParameter(url,"idOffre");url=removeURLParameter(url,"idOffreAMettreEnSelection");url=removeURLParameter(url,"indexFin");url=removeURLParameter(url,"jeton");url=removeURLParameter(url,"provenance");window.history.replaceState({},document.title,url)},100);$(this).off("hidden.bs.modal");$(".result.active").removeClass("active");$("body").removeClass("modal-details-open")})}function removeURLParameter(url,parameter){var urlparts=
url.split("?");if(urlparts.length>=2){var prefix=encodeURIComponent(parameter)+"\x3d";var pars=urlparts[1].split(/[&;]/g);for(var i=pars.length;i-- >0;)if(pars[i].lastIndexOf(prefix,0)!==-1)pars.splice(i,1);return urlparts[0]+(pars.length>0?"?"+pars.join("\x26"):"")}return url}function activer(lien){lienAfficherDetail=lien;boutonPrecedent=$(".btn.prev");boutonSuivant=$(".btn.next");dataAttributeName="data-id-offre";lire=_.debounce(ajax,500);$(document).on("afficherDetail",function(event,idOffre){idOffreCourante=
idOffre;setFocusOnOffresOnVoletHidden();var modal=$("#PopinDetails");if(modal){chargerDetail(idOffre);modal.modal("show");$("body").addClass("modal-details-open")}});$(document).on("click",'button[id*\x3d"btnEnvoiAmi"]',function(event){ajax("/offres/recherche.rechercheoffre.voletdetail:rafraichirstatutmail",$.noop)});$(document).on("maj-resultats",function(event,objOffres){nbTotalOffres=objOffres.total;$(".nb-total").html(nbTotalOffres);offres=_.map(objOffres.offres,function(offre){return offre.content.id});
if(indexOffreDemande){chargerDetail(offres[indexOffreDemande]);indexOffreDemande=null}else if(idOffreCourante)chargerDetail(idOffreCourante);majBoutonsPagination()});boutonPrecedent.off("click").on("click",function(event){chargerDetail($(this).attr(dataAttributeName),"Precedent")});boutonSuivant.off("click").on("click",function(event){var idOffre=$(this).attr(dataAttributeName);if(idOffre===undefined){indexOffreDemande=offres.length;$(".results-more .btn").trigger("click");loader()}else chargerDetail(idOffre,
"Suivant")})}function loader(){var templateLoader=$("#detailOffreVolet-loader").html();$("#detailOffreVolet").html(templateLoader);var templateContactLoader=$("#contactOffreVolet-loader").html();$("#contactOffreVolet").html(templateContactLoader);var templateSignalerLoader=$("#signalerOffreVolet-loader").html();$("#signalerOffreVolet").html(templateSignalerLoader)}function majBoutonsPagination(){if(idOffreCourante==undefined||offres==undefined)return;var firstIndexOffreCourante=_.indexOf(offres,idOffreCourante);
var lastIndexOffreCourante=_.lastIndexOf(offres,idOffreCourante);if(firstIndexOffreCourante<0||lastIndexOffreCourante<0)return;if(lastIndexOffreCourante===nbTotalOffres-1)$(".item-courant").html(lastIndexOffreCourante+1);else $(".item-courant").html(firstIndexOffreCourante+1);if(firstIndexOffreCourante===0){boutonPrecedent.prop("disabled",true);boutonPrecedent.removeAttr(dataAttributeName)}else{boutonPrecedent.prop("disabled",false);boutonPrecedent.attr(dataAttributeName,offres[firstIndexOffreCourante-
1])}if(lastIndexOffreCourante===nbTotalOffres-1||lastIndexOffreCourante>=999){boutonSuivant.prop("disabled",true);boutonSuivant.removeAttr(dataAttributeName)}else{boutonSuivant.prop("disabled",false);if(lastIndexOffreCourante===offres.length-1)boutonSuivant.removeAttr(dataAttributeName);else boutonSuivant.attr(dataAttributeName,offres[lastIndexOffreCourante+1])}}function chargerDetail(idOffre,navigation){loader();idOffreCourante=idOffre;majBoutonsPagination();if(!navigation)navigation="";if(lienAfficherDetail.indexOf("?")>
0)lire(lienAfficherDetail+"\x26idOffre\x3d"+idOffreCourante+(offres?"\x26indexFin\x3d"+offres.length:"")+"\x26navigation\x3d"+navigation,{success:function(){selection.init("Detail_offre")}});else lire(lienAfficherDetail+"?\x26idOffre\x3d"+idOffreCourante+"\x26navigation\x3d"+navigation,{success:function(){selection.init("Detail_offre")}});activerOuDesactiverElementDansResultat(idOffre);var indexQuery=window.location.href.indexOf("?");if(indexQuery>0)history.replaceState("detail","Page détail",window.location.href.replace(window.location.href,
window.location.href.substr(0,indexQuery)+"/detail/"+idOffreCourante));else history.replaceState("detail","Page détail",window.location.href.replace(/[^/]+$/g,idOffreCourante))}function envoyerTags(page,provenance,authent,provenanceSite,manqueCandidat){setTagDePage({elem:this,level2:91,chapter1:"Detail_offre",chapter2:page,name:provenance});setCustomVarsSiteSpecifique({technology:"Tapestry",category:"Candidat",authent:authent,pn:"pn055",indicateurSite4:provenanceSite});var customVarsPage=tc_vars.customObjects||
{};customVarsPage.APDC=manqueCandidat;if(idOffreCourante)customVarsPage.numOffre=idOffreCourante;setCustomVarsPage(customVarsPage);dispatchSmartTagAvecVerification()}function activerOuDesactiverElementDansResultat(idOffre){$(".result.active").removeClass("active");var elementResultat=$(".result[data-id-offre\x3d"+idOffre+"]");elementResultat.addClass("active");if(!elementResultat.hasClass("seen")){elementResultat.addClass("seen");elementResultat.find("img").tooltip()}}function remiseEnPlaceFocus(){$(document).trigger("contentLoaded.bs.modal")}
function trapFocusVolet(element,action,namespace){var element=document.querySelector(element);if(element){var focusableVoletEls=element.querySelectorAll('a[href], button, textarea, input[type\x3d"text"], input[type\x3d"radio"], input[type\x3d"checkbox"], select'),firstFocusableVoletEl=focusableVoletEls[0];lastFocusableVoletEl=focusableVoletEls[focusableVoletEls.length-2];KEYCODE_TAB=9;if(action=="add")element.addEventListener("keydown",handleKeyDown,true);else if(action=="remove")element.removeEventListener("keydown",
handleKeyDown,true);function handleKeyDown(e){var isTabPressed=e.key==="Tab"||e.keyCode===KEYCODE_TAB;if(!isTabPressed)return;if(e.shiftKey)if(document.activeElement===firstFocusableVoletEl){lastFocusableVoletEl.focus();e.preventDefault()}else{if($(document.activeElement).hasClass("wrap-panel-map")){lastFocusableVoletEl.focus();e.preventDefault()}}else if(document.activeElement===lastFocusableVoletEl){firstFocusableVoletEl.focus();e.preventDefault()}}}}})}).call(this);
(function(){define("offre/filtres",["jquery","t5/core/zone","underscore","bootstrap/collapse"],function($,zoneManager,_){function initPlierDeplierCollapseCritere(criteresObjects){if(criteresObjects.typeContrat){$("li.fadeIn").toggleClass("hidden");$("#btn-collapse-contrats").toggleClass("displayed")}if(criteresObjects.dureeContrat)$("#collapse-type-contrat").toggleClass("in");if(criteresObjects.tempsPartiel)$("#collapse-duree-hebdo").toggleClass("in")}function initSubmitFilter(){$("#newfilters input[type\x3dcheckbox], #newfilters input[type\x3dradio], #newfilters select").on("change",
function(event){var _this=$(this);var chapter2="Activation";var chapter3;var name;if(_this.attr("id").indexOf("idExperienceNewFiltre")>=0){chapter3="Experience";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";name=_this.attr("value")}else if(_this.attr("id").indexOf("idEmissionNewFiltre")>=0){chapter3="Date_creation_offre";name=_this.attr("value")}else if(_this.attr("id").indexOf("idDomaineProfessionnelNewFiltre")>=0){chapter3="Domaine_professionnel";if(!_this.is(":checked")&&
_this.attr("type")==="checkbox")chapter2="Desactivation";name=_this.attr("value")}else if(_this.attr("id").indexOf("idQualificationNewFiltre")>=0){chapter3="Qualification";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";name=_this.attr("value")}else if(_this.attr("id").indexOf("idOffresPeuDeCandidats")>=0){chapter3="Opportunites";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";name="Opportunites"}else if(_this.attr("id").indexOf("idContratNewFiltre")>=
0){chapter3="Type_contrat";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";name=_this.attr("value")}else if(_this.attr("id").indexOf("idContratNewFiltreCollapsed")>=0){chapter3="Type_contrat";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";name=_this.attr("value")}else if(_this.attr("id").indexOf("idDureeHebdoNewFiltre")>=0){chapter3="Duree_hebdomadaire";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";
name=_this.attr("value")}else if(_this.attr("id").indexOf("salairePeriode")>=0){chapter3="Salaire";if(!_this.is(":checked")&&_this.attr("type")==="checkbox")chapter2="Desactivation";name=$('input[id*\x3d"idSalaireNewFiltre"]').val()+"_"+$("#salairePeriode")[0].options[$("#salairePeriode")[0].selectedIndex].text}if(name!=="null")tagDeClick({elem:this,chapter1:"Criteres",chapter2:chapter2,chapter3:chapter3,name:name,level2:91,type:"action"})})}function onHideFilter(){var modification=false;var clicOnListeDeroulante=
false;$(".dropdown-menu ul").on("click",function(event){event.stopPropagation()}).on("change",function(){modification=true});$(".dropdown-menu input[type\x3dtext]").on("keypress",function(){modification=true});$("#filter-date-creation, #filter-contrat, #filter-duree-hebdo, #filter-domaine-pro, #filtre-experience, #more-filter").on("click",function(event){if(modification)clicOnListeDeroulante=true});$("#btn-collapse-contrats").on("click",function(event){event.stopPropagation()});$("#salairePeriode").on("click",
function(event){event.stopPropagation()});$("#btn-aide-offres-peu-de-candidats").on("click",function(event){event.stopPropagation()});$("#newfilters .dropdown").on("hidden.bs.dropdown",function(){if(modification&&!clicOnListeDeroulante)$('form[id*\x3d"rechercheForm"]').submit();else clicOnListeDeroulante=false})}function initDureeContrat(){dureeContratMinimumSelectionne=parseFloat(Math.round($("#idDureeContratMin").val()*100)/100).toFixed(2);dureeContratMaximumSelectionne=parseFloat(Math.round($("#idDureeContratMax").val()*
100)/100).toFixed(2);$("#idDureeContratMin").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeContratMax").is(":focus")){var nouvelleValeurDureeMin=parseFloat(Math.round($("#idDureeContratMin").val()*100)/100).toFixed(2);if(dureeContratMinimumSelectionne!==nouvelleValeurDureeMin){tagDeClick({elem:this,chapter1:"Criteres",chapter2:"Activation",chapter3:"Duree_contrat",name:$("#idDureeContratMin").val()+"_a_"+$("#idDureeContratMax").val()+"_mois",level2:91,type:"action"});dureeContratMinimumSelectionne=
nouvelleValeurDureeMin}}},1E3)});$("#idDureeContratMax").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeContratMin").is(":focus")){var nouvelleValeurDureeMax=parseFloat(Math.round($("#idDureeContratMax").val()*100)/100).toFixed(2);if(dureeContratMaximumSelectionne!==nouvelleValeurDureeMax){tagDeClick({elem:this,chapter1:"Criteres",chapter2:"Activation",chapter3:"Duree_contrat",name:$("#idDureeContratMin").val()+"_a_"+$("#idDureeContratMax").val()+"_mois",level2:91,type:"action"});
dureeContratMaximumSelectionne=nouvelleValeurDureeMax}}},1E3)})}function initAffichageDureeHebdo(){$("#duree_hebdo input[type\x3dcheckbox]").on("change",function(){var _this=$(this);if(_this.attr("value")=="2")if(_this.is(":checked"))$("#collapse-duree-hebdo").collapse("show");else{$("#collapse-duree-hebdo").collapse("hide");$("#idDureeHebdoNewFiltreMin").val("");$("#idDureeHebdoNewFiltreMax").val("")}})}function initDureeHebdo(){dureeContratHebdoMinSelectionne=parseFloat(Math.round($("#idDureeHebdoNewFiltreMin").val()*
100)/100).toFixed(2);dureeContratHebdoMaxSelectionne=parseFloat(Math.round($("#idDureeHebdoNewFiltreMax").val()*100)/100).toFixed(2);$("#idDureeHebdoNewFiltreMin").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeHebdoNewFiltreMax").is(":focus")){var nouvelleValeurDureeHebdoMin=parseFloat(Math.round($("#idDureeHebdoNewFiltreMin").val()*100)/100).toFixed(2);if(dureeContratHebdoMinSelectionne!==nouvelleValeurDureeHebdoMin)dureeContratHebdoMinSelectionne=nouvelleValeurDureeHebdoMin}},
1E3)});$("#idDureeHebdoNewFiltreMax").on("keyup",function(event){setTimeout(function(){if(!$("#idDureeHebdoNewFiltreMin").is(":focus")){var nouvelleValeurDureeHebdoMax=parseFloat(Math.round($("#idDureeHebdoNewFiltreMax").val()*100)/100).toFixed(2);if(dureeContratHebdoMaxSelectionne!==nouvelleValeurDureeHebdoMax)dureeContratHebdoMaxSelectionne=nouvelleValeurDureeHebdoMax}},1E3)})}function initAffichageDureeContrat(){$("#type_contrat input[type\x3dcheckbox]").on("change",function(event){var _dureeContratCollapse=
$("#collapse-type-contrat");var checkboxCollapse=$("#type_contrat input[type\x3dcheckbox]");var countMustCollapse=_.countBy(checkboxCollapse,function(contrat){return $(contrat).is(":checked")&&($(contrat).attr("value")==="CDS"||($(contrat).attr("value")==="CDD"||($(contrat).attr("value")==="MIS"||$(contrat).attr("value")==="SAI")))}).true;if(countMustCollapse)_dureeContratCollapse.collapse("show");else{_dureeContratCollapse.collapse("hide");$("#idDureeContratMin").val("");$("#idDureeContratMax").val("")}})}
function initCollapse(){$("[data-toggle\x3dmore]").click(function(e){$(this).toggleClass("displayed"),$($(this).attr("data-target")).find(".fadeIn").toggleClass("hidden").end().find(".fadeIn:first").attr("tabindex","-1").focus()});$("[data-toggle\x3dcollapse-opportunites]").click(function(e){$(this).toggleClass("displayed"),$($(this).attr("data-target")).toggleClass("in").end().focus()})}function initSalaireMinimum(){salaireMinimumSelectionne=parseFloat(Math.round($("#idSalaireNewFiltre").val()*100)/
100).toFixed(2);$("#idSalaireNewFiltre").on("keyup",function(event){setTimeout(function(){var nouvelleValeurSalaire=parseFloat(Math.round($("#idSalaireNewFiltre").val()*100)/100).toFixed(2);if(salaireMinimumSelectionne!==nouvelleValeurSalaire){tagDeClick({elem:this,chapter1:"Criteres",chapter2:"Activation",chapter3:"Salaire",name:nouvelleValeurSalaire+"_"+$("#salairePeriode")[0].options[$("#salairePeriode")[0].selectedIndex].text,level2:91,type:"action"});salaireMinimumSelectionne=nouvelleValeurSalaire}},
5E3)})}function initInputTextPatternEtEmpecherCopierColler(){$("#newfilters input[type\x3dtext]").on("keypress",function(event){var REG=/[0-9.,]/gi;var key=String.fromCharCode(event.which);return[8,9,37,39,46].indexOf(event.keyCode)!=-1||REG.test(key)});$("#newfilters input[type\x3dtext]").on("paste",function(e){e.preventDefault()})}var soumettreFormulaireAvecDelai;function initDebounce(){soumettreFormulaireAvecDelai=_.debounce(soumettreFormulaireDirect,1E3)}function soumettreFormulaireDirect(){$('form[id*\x3d"rechercheForm"]').submit()}
function initDebounceOnOffresPartenaires(){initDebounce();$(document).on("change",'input[id*\x3d"idoffresPartenaires"]',function(event){soumettreFormulaireAvecDelai()})}function initFiltres(data){initCollapse();initAffichageDureeContrat();initDureeContrat();initAffichageDureeHebdo();initDureeHebdo();initSubmitFilter();initDebounceOnOffresPartenaires();initPlierDeplierCollapseCritere(data);onHideFilter();initSalaireMinimum();initInputTextPatternEtEmpecherCopierColler()}return{init:initFiltres}})}).call(this);